### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by billiejoenahema** [billiejoenahema/Vocabulability#14]
- [x] change regex to custom validation in form request
- [x] make policy & apply API route
- [x] apply vue3-loading-overlay
- [x] make a command to generate administrator account
- [x] update tests
- [x] install php-ide-helper
- [ ] display example entries on the input form
